UPDATE osm_point set place = 'town' where place='city' and name ='Reus';
 UPDATE osm_point set place = 'town' where place='city' and name ='Segovia';
 UPDATE osm_point set place = 'town' where place='city' and name ='Guadalajara';
 UPDATE osm_point set place = 'town' where place='city' and name ='Alcobendas';
 UPDATE osm_point set place = 'town' where place='city' and name ='Parla';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'Henares$';
 UPDATE osm_point set place = 'town' where place='city' and name ='Getafe';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'Ardoz$';
 UPDATE osm_point set place = 'town' where place='city' and name ='Fuenlabrada';
 UPDATE osm_point set place = 'town' where place='city' and name ='Cuenca';
 UPDATE osm_point set place = 'town' where place='city' and name ='Albacete';
 UPDATE osm_point set place = 'town' where place='city' and name ='Soria';
 UPDATE osm_point set place = 'town' where place='city' and name ='Valladolid';
 UPDATE osm_point set place = 'town' where place='city' and name ='Torrevieja';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^Ja.n$';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^Castell.*Plana$';
 UPDATE osm_point set place = 'town' where place='city' and name ='Dos Hermanas';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^Jerez';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^C.diz$';
 UPDATE osm_point set place = 'town' where place='city' and name ='Algeciras';
 UPDATE osm_point set place = 'town' where place='city' and name ='Marbella';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^M.laga$';
 UPDATE osm_point set place = 'town' where place='city' and name ='Huesca';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^Vitoria$';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^Vitoria';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^Ortuella';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^Donostia';
 UPDATE osm_point set place = 'town' where place='city' and name ~ '^Santander';
 UPDATE osm_point set place = 'town' where place='city' and name ~'Matar.';
 UPDATE osm_point set place = 'town' where place='city' and name ='Badalona';
 UPDATE osm_point set place = 'town' where place='city' and name ='Santa Coloma de Gramenet';
 UPDATE osm_point set place = 'town' where place='city' and name ='Sabadell';
 UPDATE osm_point set place = 'town' where place='city' and name ='Terrassa';
 UPDATE osm_point set place = 'town' where place='city' and name ='Burgos';
 UPDATE osm_point set place = 'town' where place='city' and name ='Palencia';
 UPDATE osm_point set place = 'town' where place='city' and name ='Toledo';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'Legan.s';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'Alcorc.n';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'M.stoles';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'Logro.o';
 UPDATE osm_point set place = 'town' where place='city' and name = 'Ciudad Real';
 UPDATE osm_point set place = 'town' where place='city' and name = 'Badajoz';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'M.rida';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'C.ceres';
 UPDATE osm_point set place = 'town' where place='city' and name = 'Ávila';
 UPDATE osm_point set place = 'town' where place='city' and name = 'Zamora';
 UPDATE osm_point set place = 'town' where place='city' and name = 'Coimbra';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'Castelo.Branco';
 UPDATE osm_point set place = 'town' where place='city' and name ~ 'Santo.Tirso';
 UPDATE osm_point set place = 'town' where place='city' and name = 'Braga';
 UPDATE osm_point set place = 'town' where place='city' and name = 'Pontevedra';
 UPDATE osm_point set place = 'town' where place='city' and name = 'Ourense';

