#undef _maxscale
#undef _minscale

#undef _railway_width
#undef _railway_tie_size

#undef _motorway_width
#undef _motorway_link_width
#undef _motorway_lbl_size

#undef _trunk_width
#undef _trunk_link_width
#undef _trunk_lbl_size

#undef _display_primary
#undef _primary_width
#undef _primary_link_width
#undef _primary_lbl_size
#undef _primary_lbl_ref

#undef _display_secondary
#undef _secondary_width
#undef _secondary_link_width
#undef _secondary_lbl_size

#undef _display_tertiary
#undef _display_tertiary_single
#undef _display_tertiary
#undef _tertiary_width
#undef _tertiary_lbl_size

#undef _display_other
#undef _label_other
#undef _other_width
#undef _other_lbl_size

#undef _display_track
#undef _label_track
#undef _track_width
#undef _track_lbl_size

#undef _path_width

#undef _display_pedestrian
#undef _label_pedestrian
#undef _pedestrian_width
#undef _pedestrian_lbl_size 

#undef _data_expr
#undef _display_tunnels

#undef _display_place_symbol
#undef _places_data
#undef _display_capitals
#undef _capital_size
#undef _capital_lbl_size
#undef _display_cities
#undef _city_size
#undef _city_lbl_size
#undef _display_towns
#undef _town_size
#undef _town_lbl_size
#undef _country_lbl_size
#undef _display_villages
#undef _village_size
#undef _village_lbl_size
#undef _display_other_places
#undef _other_place_size
#undef _other_place_lbl_size
